using Pgvector;

namespace GjirafaNewsAPI.Domain.Entities;

/// <summary>
/// Vector representation of an article's text, generated by an embedding model
/// (currently OpenAI <c>text-embedding-3-small</c>, 1024 dimensions via the
/// Matryoshka <c>dimensions</c> request parameter). Stored in a separate table
/// so the heavy <c>vector</c> column never travels with normal article reads,
/// and so re-embedding doesn't touch the article row.
///
/// One row per article (unique FK on <see cref="ArticleId"/>). When the source
/// article is hard-deleted, the embedding is cascade-deleted with it. Article
/// soft-deletes do <em>not</em> remove the embedding — the article row still
/// exists, just hidden by the global query filter.
/// </summary>
public class ArticleEmbedding : BaseEntity
{
    public int Id { get; set; }

    public int ArticleId { get; set; }
    public virtual Article Article { get; set; } = null!;

    /// <summary>1024-dimensional embedding from text-embedding-3-small.</summary>
    public Vector Embedding { get; set; } = null!;

    /// <summary>
    /// Embedding model identifier (e.g. "text-embedding-3-small"). Stored so we
    /// can detect rows produced by a different model and re-embed them after a
    /// model swap, without ambiguity.
    /// </summary>
    public string Model { get; set; } = string.Empty;

    /// <summary>
    /// SHA-256 hex of the text that was embedded (typically Title + Summary +
    /// Content). Lets us skip re-embedding when the article hasn't actually
    /// changed in a way that affects the vector.
    /// </summary>
    public string ContentHash { get; set; } = string.Empty;
}
